# Generated by Django 6.1 on 2026-08-19 21:24

import django.db.models.deletion
import file_upload.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.CharField(max_length=48, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.CharField(max_length=48, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "transcriptions",
                    models.ManyToManyField(
                        related_name="books", to="file_upload.transcription"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lilypond_source",
                    models.FileField(
                        upload_to=file_upload.models.revision_lilypond_path
                    ),
                ),
                (
                    "template_tag",
                    models.CharField(
                        default=file_upload.models.get_latest_template_version,
                        help_text="Git tag from LilyPond template repository",
                        max_length=255,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="file_upload.transcription",
                    ),
                ),
            ],
            options={
                "ordering": ("index",),
                "unique_together": {("transcription", "index")},
            },
        ),
    ]
