# Generated by Django 6.1 on 2026-08-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="index",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
