# Generated by Django 6.1 on 2026-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0002_alter_revision_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdf"),
        ),
    ]
