# Generated by Django 6.1 on 2026-08-21 03:26

import file_upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0003_revision_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="transcriptions",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="file_upload.transcription"
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to=file_upload.models.revision_pdf_path
            ),
        ),
    ]
