# Generated by Django 6.1 on 2026-08-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0005_remove_book_transcriptions_alter_book_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="transcriptions",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                through="file_upload.BookContents",
                to="file_upload.transcription",
            ),
        ),
    ]
